dist: trusty
language: rust
rust: nightly

addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

before_script:
- rustup component add rust-src
- cd .. && cargo install xargo --verbose && cd stm32f7-discovery

script:
- xargo build

