language: rust
rust: nightly

before_script:
- curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- rustup component add rust-src
- cd .. && cargo install xargo --verbose && cd stm32f7-discovery
- rustup toolchain install nightly-arm-unknown-linux-gnueabi
- export PATH=$HOME/.cargo/bin:$PATH

script:
- xargo build

