[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "novemb-rs-stm32f7"
version = "0.1.0"

[[bin]]
doc = false
name = "novemb-rs-stm32f7"

[dependencies]
alloc-cortex-m = "0.2.1"
bit_field = "0.7.0"
cortex-m = "0.1.4"
r0 = "0.1.0"
rlibc = "1.0.0"
spin = "0.4.5"
volatile = "0.2.1"

[dependencies.arrayvec]
default-features = false
version = "0.3.20"

[dependencies.embedded]
default-features = false
git = "https://github.com/embed-rs/embedded-rs.git"

[dependencies.embedded_stm32f7]
git = "https://github.com/embed-rs/embedded_stm32f7.git"

[dependencies.smoltcp]
default-features = false
version = "0.2.1"

[profile]

[profile.release]
lto = true
