[package]
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
name = "novemb-rs-stm32f7"
version = "0.1.0"

[[bin]]
doc = false
name = "novemb-rs-stm32f7"

[dependencies]
bit_field = "0.6.0"
compiler-builtins-snapshot = "0.0.20161008+c56faf22abb39724008148d58f12bcd43b6d236b"
cortex-m = "0.1.4"
r0 = "0.1.0"
rlibc = "1.0.0"
volatile = "0.2.0"

[dependencies.arrayvec]
default-features = false
version = "0.3.20"

[dependencies.embedded]
git = "https://github.com/embed-rs/embedded-rs.git"

[dependencies.embedded_stm32f7]
git = "https://github.com/embed-rs/embedded_stm32f7.git"

[profile]

[profile.release]
lto = true
